name = "snake-game"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./dist"

[env.production]
name = "snakegame"
routes = [
  { pattern = "snakegame.tkvern.com", zone_name = "tkvern.com" }
]
